* strats
** how to elicit strategies
/Associate./

"As you go back to that time now I want you to step into your body, see what you saw at the time, hear the sounds around you and really feel all the feelings of being right there doing ____"

"What's the very first thing that has to happen so that you know it's time to ____?"

/Go through all the senses to avoid bias./

"Was it something you saw?

Was it a sound that you heard or something that somebody said to you or something you said to yourself?

Was it a feeling that you had somewhere in your body?

Or a particular scent or the taste of something?"

/Once you have the first step, go on./

"What was the second thing that happened?

What happened next?"

/Once you've completed the strategy elicitation process, you should feel free to repeat the process as many times as you need to ensure that your elicitation is accurate./

** how to change strategies

/Elicitation was by association ("go into"), changing is by dissasociation ("teach me")./

"Can you teach me how to X?

Imagine I was going to take your place for a day ~ can you teach me how to X so that I can do it in exactly the same way? Because I wouldn't want to forget about this problem."

/Run the strategy step by step./

"What's the first thing that has to happen that lets me know it's time to X? Do I hear something, see something, feel something, say something to myself? etc... etc..."

"What should I do next? etc. etc."

For each step in the strategy, purposely mismatch the key sensory modality using an example which is the polar opposite of the experience that the person running the strategy would have.

For example, the person says to herself, "Oh no, this is going to be really scary."
> 'And what voice should I say that in? Is it a really high pitched voice like Mickey Mouse?'

Anything that sounds like a silly idea is great - to scratch up the strategy. Be sure to maintain rapport, allowing them to consider behaviors radically different to those they are used to.

Pace and lead them in the direction of new behavioral choices.

"No, it's not a really high pitched voice like Mickey Mouse."

> 'Well, could it be? And if it were, would it still work?'

In order to answer this question, the person now has to imagine actually performing this alternate behavior, which is the polar opposite of what they would normally do at this step of the strategy. To do this effectively they must fully associate into this alternative behavior. To process your words and respond to your questions the person will have to mentally "rehearse" each alternative behavior in the context of their strategy.
